name: non latain
description: ラテン文字を持たないcheckboxをもつissue
labels: []
body:

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting a bug, please make sure following checks.
      options:
        - label: ラテン文字を持たないチェックボックス
          required: true
        - label: latin文字を持つチェックボックス
          required: true

  - type: textarea
    attributes:
      label: body
      description: ラテン文字なissue
